cd figures
#pdflatex avgsentencoder.tex
#pdflatex rnnsentencoder.tex
#pdflatex cnnsentencoder.tex
pdflatex s2s_extractor.tex
pdflatex rnnextractor.tex
pdflatex clextractor.tex
pdflatex sr_extractor.tex
cd ..
pdflatex dlextsum.emnlp18.tex
